version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
      image: mysql:8.0.21
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_PASSWORD: 'password'
          MYSQL_DATABASE: 'dvba'
      volumes:
        - ./database:/docker-entrypoint-initdb.d